version: '3'

services:
  icecast:
    build:
      context: ./icecast
    ports:
      - "8000:8000"
    volumes:
      - ./icecast/icecast.xml:/etc/icecast2/icecast.xml
    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - icecast
    restart: unless-stopped

